matrix:
  include:
    - os: linux
      language: cpp
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - clang-format-3.9
      install:
        - mkdir .local
        - ln -s `which g++-7` .local/g++
        - PATH=${PWD}/.local:${PATH}
      script:
        - ./test.py example/cpp

before_install:
  - yes | pyenv install 3.6.3
  - pyenv global 3.6.3
  - pip install --upgrade pip
  - pip install requests termcolor

sudo: false

notifications:
  email: false
