matrix:
  include:
    - os: linux
      language: cpp
      compiler: "g++-7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - clang-format-3.9
      install:
        - mkdir .local
        - ln -s `which g++-7` .local/g++
        - PATH=${PWD}/.local:${PATH}
      script:
        - g++ --version
        - ./test.py example/cpp

    - os: linux
      language: csharp
      mono: "3.12.0"
      script:
        - mono --version
        - ./test.py example/csharp

    - os: linux
      language: go
      go: "1.10"
      script:
        - go version
        - ./test.py example/go

    - os: linux
      language: haskell
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - cabal-install-2.2
            - ghc-8.4.3
      install:
        - mkdir .local
        - ln -s `which ghc-8.4.3` .local/ghc
        - PATH=${PWD}/.local:${PATH}
      script:
        - ghc --version
        - ./test.py example/haskell

    - os: linux
      language: java
      jdk: openjdk10
      script:
        - java --version
        - ./test.py example/java

    - os: linux
      language: python
      python: "3.6"
      script:
        - python --version
        - ./test.py example/python

before_install:
  - yes | pyenv install 3.6.3
  - pyenv global 3.6.3
  - pip install --upgrade pip
  - pip install requests termcolor

sudo: false

notifications:
  email: false
