dist: xenial

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

matrix:
  include:
    - os: linux
      language: cpp
      compiler: gcc
      script:
        - gcc --version
        - red-baron example/c

    - os: linux
      language: cpp
      compiler: "g++-7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - clang-format-3.9
      script:
        - g++ --version
        - CXX=g++-7 red-baron example/cpp

    - os: linux
      language: csharp
      mono: "3.12.0"
      script:
        - mono --version
        - red-baron example/csharp

    - os: linux
      language: d
      d: "dmd-2.081.2"
      script:
        - dmd --version
        - red-baron example/d

    - os: linux
      language: go
      go: "1.10.x"
      script:
        - go version
        - red-baron example/go

    - os: linux
      language: haskell
      ghc: "8.4.3"
      install:
        - alias cabal=echo
      script:
        - ghc --version
        - GHC=ghc-8.4.3 red-baron example/haskell

    - os: linux
      language: java
      jdk: openjdk10
      script:
        - java --version
        - red-baron example/java

    - os: linux
      language: ocaml
      env:
        - LANG="OCaml 4.07.0"
      install:
        - sudo add-apt-repository --yes ppa:avsm/ppa
        - sudo apt-get update
        - sudo apt-get install opam
        - opam init -y
        - if [ -e ${HOME}/.opam/4.07.0 ]; then
            opam switch 4.07.0;
          else
            opam switch create 4.07.0;
          fi
        - eval $(opam config env)
        - opam config var root
        - opam install -y num batteries
      script:
        - ocaml -version
        - red-baron example/ocaml

    - os: linux
      language: python
      python: "3.6"
      script:
        - python --version
        - red-baron example/python3

    - os: linux
      language: ruby
      rvm: "2.2"
      script:
        - ruby --version
        - red-baron example/ruby

    - os: linux
      language: rust
      rust: 1.27.2
      script:
        - rustc --version
        - red-baron example/rust

    - os: linux
      language: python
      python: "3.6"
      env:
        - ENV='Lint'
      script:
        - pip install autopep8 flake8
        - autopep8 -r . --diff
        - flake8

before_install:
  - pip3 install --upgrade pip --user
  - pip3 install . --user

if: branch = master OR type in (pull_request)

cache:
  - apt
  - directories:
    - ${HOME}/.red_baron
    - ${HOME}/.opam

sudo: false

notifications:
  email: false
