#!/usr/bin/env python

import argparse
from pathlib import Path
import sys

import scripts

if __name__ == '__main__':
    if sys.version_info[:3] < (3, 4, 0):
        Exception('Use Python 3.4 or later')

    parser = argparse.ArgumentParser()
    parser.add_argument(
        'target', nargs='?', help='target directory', default='.')
    args = parser.parse_args()
    target = Path.cwd() / args.target

    scripts.test_recursive(target)
