#!/usr/bin/env python

import argparse
from pathlib import Path
import sys

import scripts

if __name__ == '__main__':
    if sys.version_info[:3] < (3, 5, 0):
        Exception('Use Python 3.5 or later')

    parser = argparse.ArgumentParser()
    parser.add_argument(
        'targets', nargs='+', help='The target directory', default='.')
    parser.add_argument(
        '--redownload', help='Redownload testcase', action='store_true')
    parser.add_argument(
        '--lines', '-n', nargs='?', help='Output first N lines', default=10)
    args = parser.parse_args()

    scripts.test(args.targets, args.redownload, int(args.lines))
