#!/usr/bin/env python

import argparse
from pathlib import Path
import sys

import scripts

if __name__ == '__main__':
    if sys.version_info[:3] < (3, 4, 0):
        Exception('Use Python 3.4 or later')

    parser = argparse.ArgumentParser()
    parser.add_argument(
        'target', nargs='?', help='The target directory', default='.')
    parser.add_argument(
        '--redownload', help='Redownload testcase', action='store_true')
    args = parser.parse_args()
    target = Path.cwd() / args.target
    redownload = args.redownload

    scripts.test_recursive(target, redownload)
